// Every player-facing string. The font build reads this file to bake exactly
// the glyphs the game needs.
(function (root) {
  'use strict';
  const strings = {
    // Title and shell
    'title.name': 'NIGHT SHIFT FREQUENCY',
    'title.place': 'LOWTIDE · HARBOR MART · 1 A.M.',
    'title.start': 'START SHIFT',
    'ui.radioHint': 'Click the radio to tune it',
    'title.hint': 'Click to play · sound starts after you begin',
    'end.title': 'SHIFT OVER',
    'end.records': 'WHAT YOU RECORDED',
    'end.again': 'ANOTHER SHIFT',
    'end.seed': 'SEED {seed}',
    'end.note': 'Record it differently and the radio reads another letter.',

    // The night staff sign-in sheet
    'sheet.store': 'HARBOR MART',
    'sheet.title': 'NIGHT STAFF SIGN-IN',
    'sheet.date': 'DATE',
    'sheet.name': 'NAME',
    'sheet.in': 'IN',
    'sheet.out': 'OUT',
    'sheet.erase': 'DEL',
    'sheet.signIn': 'SIGN IN',
    'sheet.signOut': 'SIGN OUT',
    'sheet.hintIn': "Write your name on tonight's line.",
    'sheet.hintOut': 'Five o\'clock. The radio has stopped.',
    'sheet.defaultName': 'ROBIN',

    // Items as the register names them
    'item.coffee': 'ICED COFFEE',
    'item.lasagne': 'BEEF LASAGNE',
    'item.tea': 'GREEN TEA',
    'item.water': 'WATER 500ML',
    'item.sandwich': 'EGG SANDWICH',
    'item.juice': 'ORANGE JUICE',
    'item.cola': 'COLA 500ML',
    'item.bread': 'SWEET ROLL',
    'item.spareKey': 'SPARE KEY',

    // POS screen
    'phone.title': 'SETTINGS',
    'phone.master': 'VOLUME',
    'phone.radio': 'RADIO',
    'phone.sounds': 'SOUNDS',
    'phone.silent': 'SILENT MODE',
    'phone.on': 'ON',
    'phone.off': 'OFF',
    'phone.back': 'BACK',

    'pos.ready': 'READY',
    'pos.waiting': 'WAITING FOR ITEMS',
    'pos.total': 'TOTAL {amount}',
    'pos.items': '{count} ITEMS',
    'pos.reading': 'READING',
    'pos.cash': 'CASH',
    'pos.card': 'CARD',
    'pos.rescanPending': 'RE-SCAN PENDING',
    'pos.register': 'REG#02',
    'pos.recordPending': 'PRESS REC KEY',
    'pos.recordSaved': 'RECORD SAVED',
    'pos.mismatch': 'RECORD MISMATCH',
    'pos.link': 'LINK #{order}',
    'pos.closed': 'SHIFT CLOSED',
    'pos.sales': 'SALES {amount}',
    'pos.printReport': 'PRINT SHIFT REPORT',

    // Record panel on the POS
    'rec.title': 'REG#02 / TRANSACTION RECORD',
    'rec.time': 'TIME',
    'rec.item': 'ITEM',
    'rec.register': 'REGISTER',
    'rec.rescan': 'RE-SCAN',
    'rec.pending': 'PENDING',
    'rec.awaiting': 'AWAITING SCAN',
    'rec.linked': 'LINKED SALE #{order}',
    'rec.entry': 'ENTRY',
    'rec.origin': 'ORIGIN',
    'rec.verify': 'VERIFY',
    'rec.from': 'FROM',
    'rec.saved': 'SAVED ENTRY',
    'rec.preview': 'WILL SAVE',
    'rec.instruction': 'Return to the counter and scan it again.',
    'rec.choose': 'Choose how to record this sale',
    'rec.keep': 'KEEP REGISTER ENTRY',
    'rec.correct': 'CORRECT TO ITEM',
    'rec.linkedChoice': 'USE ENTRY FROM #{order}',
    'rec.independent': 'USE THIS SCAN',
    'rec.back': 'BACK TO COUNTER',
    'rec.save': 'SAVE RECORD',
    'rec.paid': 'PAID TRANSACTIONS',
    'rec.none': 'NONE YET',
    'rec.keys': '↑↓ select · Enter confirm · Esc close',
    'origin.REGISTER': 'REGISTER',
    'origin.MANUAL': 'MANUAL',
    'verify.AUTO': 'AUTO',
    'verify.CURRENT_SCAN': 'CURRENT SCAN',
    'verify.LINKED_HISTORY': 'LINKED HISTORY',

    // Shift report
    'report.title': 'SHIFT REPORT',
    'report.sales': 'SALES',
    'report.orders': 'TRANSACTIONS',
    'report.overrides': 'MANUAL EDITS',
    'report.links': 'LINKED ENTRIES',
    'report.verified': 'CURRENT SCANS',
    'report.continue': 'Click to continue',

    // Customer lines
    'say.cash': 'Cash.',
    'say.card': 'Card.',
    'say.noBag': 'No bag.',
    'say.earlyPayment': 'These first.',
    'say.earlyBag': 'Not yet.',
    'say.redundantScan': 'Same one.',
    'say.earlyHeat': 'After, yeah.',
    'say.unneededHeat': 'Not that one.',
    'say.bagBeforeHeat': 'Hot first.',
    'say.heatRequest': 'Heat this, please.',
    'say.scanAfterPay': 'Already paid.',
    'say.rain1': 'Still raining.',
    'say.rain2': 'Left my umbrella at the pier.',
    'say.rainScan': 'Good call.',
    'say.rainExit': 'Stay dry.',
    'say.boat1': 'Just off the boat. Starving.',
    'say.boatExit': 'Cheers.',
    'say.milk1': 'Only came in for milk.',
    'say.milkScan': '...forgot the milk.',
    'say.milkExit': 'Back in a second.',
    'say.awake1': "Couldn't sleep.",
    'say.radio1': 'You listening to Night Ferry too?',
    'say.radioScan': "June's voice puts me right out.",
    'say.radioExit': 'Night.',
    'say.tower1': "That red light across the bay's on again.",
    'say.towerExit': 'Get home early.',
    'say.nell1': "Yeah, I'm here.",
    'say.nell2': "I'll leave the key at the shop. Just come get it.",
    'say.nellRescan': 'Something wrong?',
    'say.nellSecondRescan': 'Still doing it?',
    'say.nellConfirmEarly': 'Run it again?',
    'say.nellKeep': 'It says... key?',
    'say.nellCorrect': 'You can change those?',
    'say.nellExit': "...Yeah. It's here.",
    'say.stayed1': "I'm here for the key.",
    'say.stayed2': 'She said she left it here.',
    'say.stayedScan': 'Same one as before.',
    'say.stayedKeepLinked': "So that's the one.",
    'say.stayedKeepIndependent': '...Another one?',
    'say.stayedCorrectLinked': "It's just a cola.",
    'say.stayedCorrectIndependent': "It wasn't a key a minute ago.",
    'say.stayedExit': '...Thanks.',

    // Radio: FM 87.6 Night Ferry, host June
    'radio.intro1': "This is FM 87.6, Night Ferry. I'm June.",
    'radio.intro2': 'One a.m. Good evening to everyone still awake.',
    'radio.o1': "Rain until dawn. The ferry's suspended — hang in there, dock crew.",
    'radio.o2': 'A listener requested an old song for the night clerk at the corner store.',
    'radio.o3a': 'The old relay tower across the bay has been dead for twelve years.',
    'radio.o3b': 'But on rainy nights, people swear they hear it transmitting.',
    'radio.o4': 'Lost and found: one yellow rain boot at the pier. Left foot.',
    'radio.o5a': 'Next message...',
    'radio.o5b': '"I left the spare key at Harbor Mart. My sister will pick it up."',
    'radio.o5c': "...It isn't signed.",
    'radio.o6a': 'Sorry — the signal got messy for a moment.',
    'radio.o6b': "If you heard another station, that wasn't us.",
    'radio.o7': "Rain's easing. Hold on a little longer — it's nearly light.",
    'radio.o8a': 'We got that message again. Word for word.',
    'radio.o8b': "Only this time, it's signed by her sister.",
    'radio.endKeepLinked1': 'One last letter: "I got the key. The door was open, the lights were on."',
    'radio.endKeepLinked2': '"My sister was waiting inside. She looks exactly like me."',
    'radio.endKeepIndependent1': 'One last letter: "There are two keys now."',
    'radio.endKeepIndependent2': '"Our house has one door. Tonight, someone came home on both sides."',
    'radio.endCorrectLinked1': 'One last letter: "The clerk said it was just a cola."',
    'radio.endCorrectLinked2': '"I sat at the door till morning. Maybe there never was a key."',
    'radio.endCorrectIndependent1': 'One last letter: "Found the key. The door opened."',
    'radio.endCorrectIndependent2': "\"But I keep thinking it isn't the one she left me.\"",
    'radio.signoff': "This is Night Ferry. It's morning. Good night.",
    'radio.static': '...kssshh...',
    'radio.staticReg': '...kssshh... REG#02...',
    'radio.echoRecord': 'REG#02. {time}. {label}, one.',
    'radio.echoOpposite': 'REG#02. 02:41. {label}. Origin: {origin}.',
    'radio.echoDoor': "She's at the door already.",
    // Between the stations: people who stayed, faintly
    'radio.taxi1': 'Car six, are you there? Fare at the pier, going nowhere in particular.',
    'radio.taxi2': "...Car six. Your meter's been running since midnight.",
    'radio.taxi3': "Nobody's called it in, Walt. Just keep driving.",
    'radio.ward1': '(a call bell) ...Bed nine. Bed nine again.',
    'radio.ward2': "Ana, you were due off at eleven. You're still on the board.",
    'radio.ward3': '(the bell once more, a long way down the corridor)',
    'radio.ferry1': 'Crossing report, Lowtide to the far shore. Sea slight. Visibility good.',
    'radio.ferry2': 'The 03:40 sailing is running on time.',
    'radio.ferry3': '...All sailings tonight remain suspended.',
    'radio.dial': 'FM {freq}',
    'radio.dialHint': 'Drag the needle, or use the arrow keys',
  };

  function t(key, vars = {}) {
    const text = strings[key];
    if (text === undefined) throw new Error('Missing string: ' + key);
    // A variable written as '@key' is itself looked up, e.g. an item label.
    return text.replace(/\{(\w+)\}/g, (_, name) => {
      const value = vars[name];
      return typeof value === 'string' && value.startsWith('@') ? t(value.slice(1)) : value ?? '';
    });
  }

  const api = { strings, t };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else (root.NSF = root.NSF || {}).strings = api;
})(globalThis);
