#!/usr/bin/env python3
"""Bake the glyphs used by js/content/strings.js into assets/font-data.js.

Uses Fusion Pixel 12px (OFL, art/font/). The runtime draws these bitmaps on the
640x360 text grid, so canvas text never anti-aliases. Requires Pillow.
Run again whenever strings change; tests/content.test.cjs checks coverage.
"""
import json
import os
import re
import subprocess

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FONT = os.path.join(ROOT, 'art/font/fusion-pixel-12px-proportional-zh_hans.ttf')
TOP, ROWS = 2, 14  # glyph rows kept from the 16px raster

strings = json.loads(subprocess.check_output(
    ['node', '-e', "process.stdout.write(JSON.stringify(require('./js/content/strings.js').strings))"],
    cwd=ROOT))
chars = set(chr(c) for c in range(32, 127))
for zh, en in strings.values():
    chars.update(re.sub(r'\{\w+\}', '', zh + en))
chars.update('¥0123456789:.#·…—×↑↓')  # symbols drawn directly by js/render/ui.js

font = ImageFont.truetype(FONT, 12)


def raster(ch):
    image = Image.new('1', (16, 16), 0)
    draw = ImageDraw.Draw(image)
    draw.fontmode = '1'
    draw.text((0, 0), ch, font=font, fill=1)
    rows = []
    for y in range(TOP, TOP + ROWS):
        bits = 0
        for x in range(16):
            if image.getpixel((x, y)):
                bits |= 1 << x
        rows.append(bits)
    return rows


missing_box = raster('\U000F0000')
glyphs = {}
for ch in sorted(chars):
    rows = raster(ch)
    if ch != ' ' and rows == missing_box:
        raise SystemExit('Font has no glyph for %r; change the string.' % ch)
    glyphs[ch] = [int(round(font.getlength(ch)))] + rows

out = os.path.join(ROOT, 'assets/font-data.js')
with open(out, 'w', encoding='utf-8') as handle:
    handle.write('// Generated by art/tools/build-font.py from Fusion Pixel 12px (SIL OFL 1.1, see art/font/OFL.txt).\n')
    handle.write('(globalThis.NSF = globalThis.NSF || {}).fontData = ')
    json.dump({'rows': ROWS, 'lineHeight': 14, 'glyphs': glyphs}, handle, ensure_ascii=False, separators=(',', ':'))
    handle.write(';\n')
print('baked', len(glyphs), 'glyphs')
